# Build container for deployment on cloud run
substitutions:
  _REGION: "us-east1"

options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--network"
      - "cloudbuild"
      - "--file"
      - "Dockerfile"
      - "--tag"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/spire-ingest-resample-worker/${_IMAGE}:${_TAG}"
      - "--tag"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/spire-ingest-resample-worker/${_IMAGE}:latest"
      - "."

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "push"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/spire-ingest-resample-worker/${_IMAGE}"
      - "--all-tags"
