# test deployment for k8s
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spire-ingest-resample-worker-dev
  labels:
    app: spire-ingest-resample-worker-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spire-ingest-resample-worker-dev
  template:
    metadata:
      labels:
        app: spire-ingest-resample-worker-dev
    spec:
      serviceAccountName: TBD
      containers:
      - name: spire-ingest-resample-worker-dev
        image: us-east1-docker.pkg.dev/contrails-301217/spire-ingest-resample-worker/spire-ingest-resample-worker-dev:latest
        env:
          - name: SPIRE_INGEST_WAYPOINTS_SUBSCRIPTION_ID
            value: "projects/contrails-301217/subscriptions/TBD"
          - name: SPIRE_WAYPOINTS_BIGQUERY_TOPIC_ID
            value: "projects/contrails-301217/topics/TBD"
          - name: SPIRE_FLIGHT_SEGMENTS_TOPIC_ID
            value: "projects/contrails-301217/topics/TBD"
          - name: REDIS_HOST
            value: TBD
          - name: REDIS_PORT
            value: TBD
          - name: LOG_LEVEL
            value: "INFO"
        resources:
          limits:
            cpu: "2"
            ephemeral-storage: "1Gi"
            memory: "8Gi"
          requests:
            cpu: "2"
            ephemeral-storage: "1Gi"
            memory: "8Gi"
