apiVersion: v1
kind: Pod
metadata:
  name: zarr-hyperdisk-inspector
  namespace: flights-pipeline-prod
spec:
  nodeSelector:
    cloud.google.com/compute-class: gcs-to-hdml-compute-class
  containers:
  - name: zarr-hyperdisk-inpector
    image: busybox
    resources:
      requests:
        cpu: "300m"
        memory: "0.5Gi"
    command:
    - sleep
    - infinity
    volumeMounts:
      - mountPath: /ecmwf-zarr-v2
        name: ecmwf-zarr-v2
  volumes:
    - name: ecmwf-zarr-v2
      persistentVolumeClaim:
        claimName: era5-zarr-gcs-pvc
