apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: spire-ingest-api-scraper-vpa
spec:
  targetRef:
    apiVersion: batch/v1
    kind: CronJob
    name: spire-ingest-api-scraper-cronjob
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: main
        controlledResources:
          - ResourceMemory
        minAllowed:
          memory: "8Gi"
        maxAllowed:
          memory: "24Gi"
