apiVersion: batch/v1
kind: CronJob
metadata:
  name: spire-ingest-api-scraper-cronjob
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 300

  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          restartPolicy: Never
          serviceAccountName: flights-pipeline-default-sa
          containers:
            - name: main
              image: {{ .Values.image | required ".Values.image is required" | quote }}
              env:
                - name: FIRESTORE_STATE_DB
                  value: {{ .Values.firestoreStateDb | required ".Values.firestoreStateDb is required" | quote }}
                - name: FIRESTORE_STATE_COLLECTION
                  value: {{ .Values.firestoreStateCollection | required ".Values.firestoreStateCollection is required" | quote }}
                - name: FIRESTORE_STATE_DOC_ID
                  value: {{ .Values.firestoreStateDocId | required ".Values.firestoreStateDocId is required" | quote }}
                - name: PUBSUB_EGRESS_TOPIC_ID
                  value: {{ .Values.pubSubEgressTopicId | required ".Values.pubSubEgressTopicId is required" | quote }}
                - name: SPIRE_RAW_WAYPOINTS_BIGQUERY_TOPIC_ID
                  value: {{ .Values.spireRawWaypointsBigQueryTopicId | required ".Values.spireRawWaypointsBigQueryTopicId is required" | quote }}
                - name: SPIRE_API_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: spire-airsafe-api-secret
                      key: API_TOKEN
                - name: LOG_LEVEL
                  value: INFO
              resources:
                requests:
                  cpu: "1"
                  # OOM when allocated memory < 7GB
                  memory: "20000Mi"
                limits:
                  cpu: "1"
                  memory: "20000Mi"
