apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spire-ingest-resample-worker-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spire-ingest-resample-worker
  minReplicas: 1
  maxReplicas: 50
  metrics:
   - external:
       metric:
        name: pubsub.googleapis.com|subscription|num_undelivered_messages
        selector:
          matchLabels:
            resource.labels.subscription_id: {{ .Values.spireIngestWaypointsSubscriptionId | required ".Values.spireIngestWaypointsSubscriptionId is required" | quote }}
       target:
         type: AverageValue
         averageValue: 100
     type: External
