# Depends on Google's Custom Metrics Adapter installed by cluster admin.
# See: https://cloud.google.com/kubernetes-engine/docs/tutorials/autoscaling-metrics#pubsub
#
# kubectl apply -f https://raw.githubusercontent.com/GoogleCloudPlatform/k8s-stackdriver/master/custom-metrics-stackdriver-adapter/deploy/production/adapter_new_resource_model.yaml

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: spire-ingest-resample-worker-scaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: spire-ingest-resample-worker
  minReplicas: 1
  maxReplicas: 50
  metrics:
    - type: External
      external:
        metric:
          name: "pubsub.googleapis.com|subscription|num_undelivered_messages"
          selector:
            matchLabels:
              resource.labels.subscription_id: {{ .Values.spireIngestWaypointsSubscriptionId | required ".Values.spireIngestWaypointsSubscriptionId is required" | splitList "/" | last | quote }}
        target:
          type: AverageValue
          averageValue: 100
