# image is the docker image uri to be deployed including the image tag
image:

# firestoreStateDb is the name of the firestore db used to store state checkpoints
firestoreStateDb:
# firestoreStateCollection is the name of the firestore collection used to store state checkpoints

firestoreStateCollection:
# firestoreStateDocId is the id of the firestore document used to store state checkpoints
firestoreStateDocId:

# pubSubEgressTopicId is the id of the pubsub topic used to publish egress messages
pubSubEgressTopicId:

# state of the cronjob
suspendCronjob:
