apiVersion: apps/v1
kind: Deployment
metadata:
  name: psdb-contrails-default-proxy
  labels:
    app: psdb-contrails-default-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: psdb-contrails-default-proxy
  template:
    metadata:
      labels:
        app: psdb-contrails-default-proxy
    spec:
      serviceAccountName: flights-pipeline-default-sa
      terminationGracePeriodSeconds: 10
      containers:
      - name: psdb-contrails-default-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.14.0
        args:
          - "--auto-iam-authn"
          - "--port=5432"
          - "--address=0.0.0.0"
          - {{ .Values.psdbConnectionName | required ".Values.psdbConnectionName is required" | quote }}
        securityContext:
          runAsNonRoot: true
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        ports:
          - containerPort: 5432
