# image is the docker image uri to be deployed including the image tag
image:

# logLevel is the python-named minimum level to emit logs
logLevel:

psdbUser:

# psdbPass: <- this is imported from k8s secret directly in the helm/k8s manifest

psdbConnectionName:

suspendCronjob: