name: flight-emissions-report-cron-deploy-dev

on:
  push:
    branches:
      - develop
    paths:
      - flight-emissions-report/**
      - .github/workflows/flight-emissions-report-cron-deploy-dev.yaml

# avoid possible race condition on multiple merges
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up GCP auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2

      - name: Set up gcloud plugins
        run: gcloud components install gke-gcloud-auth-plugin

      - name: Authorize kubectl CLI
        run: gcloud container clusters get-credentials contrails-gke-general --region us-east1

      - name: Authorize docker CLI
        run: gcloud auth configure-docker us-east1-docker.pkg.dev

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: flight-emissions-report/
          push: true
          tags: |
            us-east1-docker.pkg.dev/contrails-301217/flights-pipeline/flight-emissions-report-dev:${{ github.sha }}
            us-east1-docker.pkg.dev/contrails-301217/flights-pipeline/flight-emissions-report-dev:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy helm resources
        working-directory: flight-emissions-report/helm
        run: make deploy
        env:
          NAMESPACE: flights-pipeline-dev
          IMAGE: us-east1-docker.pkg.dev/contrails-301217/flights-pipeline/flight-emissions-report-dev:${{ github.sha }}
          LOG_LEVEL: INFO
          TWJD_TOPIC_ID: projects/contrails-301217/topics/dev-fp-twjd-ingress
          SUSPEND_CRONJOB: true
